### ISSUE TITLE
[CRITICAL] exposed oauth token!

### ISSUE THREAD

**Issue by vivax3794** [TheRealTalos/twitch-bot#2]
the oauth token is in one of the commits, I recommend you change it.

**Comment by Zach-Mac** [comment]
thx lol

**Comment by vivax3794** [comment]
@TheRealTalos also regen that token, just because you remove it from the file we can still see it in the commit log.
![image](https://user-images.githubusercontent.com/51753506/77259721-d8adb600-6c83-11ea-88bc-25df3d2b3e66.png)
